/* 
 * Version 1
 *
 * This is version 1 document
 *
 * OpenAPI spec version: 0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Elton.Phantom.Models.SwaggerDateConverter;

namespace Elton.Phantom.Models.Version1
{
    /// <summary>
    /// 远程开门
    /// </summary>
    [DataContract]
    public partial class HuoheLock :  IEquatable<HuoheLock>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HuoheLock" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HuoheLock() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HuoheLock" /> class.
        /// </summary>
        /// <param name="Id">ID (required).</param>
        /// <param name="HouseCode">house_code (required).</param>
        /// <param name="RoomCode">room_code (required).</param>
        /// <param name="Name">门锁名 (required).</param>
        /// <param name="Power">电量 (required).</param>
        /// <param name="ComuStatus">00 通信正常 01通信异常 (required).</param>
        /// <param name="Ip">设备ip (required).</param>
        /// <param name="UserId">用户ID (required).</param>
        /// <param name="HouseId">房间ID (required).</param>
        public HuoheLock(int? Id = default(int?), string HouseCode = default(string), string RoomCode = default(string), string Name = default(string), int? Power = default(int?), string ComuStatus = default(string), string Ip = default(string), int? UserId = default(int?), int? HouseId = default(int?))
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "HouseCode" is required (not null)
            if (HouseCode == null)
            {
                throw new InvalidDataException("HouseCode is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.HouseCode = HouseCode;
            }
            // to ensure "RoomCode" is required (not null)
            if (RoomCode == null)
            {
                throw new InvalidDataException("RoomCode is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.RoomCode = RoomCode;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "Power" is required (not null)
            if (Power == null)
            {
                throw new InvalidDataException("Power is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.Power = Power;
            }
            // to ensure "ComuStatus" is required (not null)
            if (ComuStatus == null)
            {
                throw new InvalidDataException("ComuStatus is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.ComuStatus = ComuStatus;
            }
            // to ensure "Ip" is required (not null)
            if (Ip == null)
            {
                throw new InvalidDataException("Ip is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.Ip = Ip;
            }
            // to ensure "UserId" is required (not null)
            if (UserId == null)
            {
                throw new InvalidDataException("UserId is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.UserId = UserId;
            }
            // to ensure "HouseId" is required (not null)
            if (HouseId == null)
            {
                throw new InvalidDataException("HouseId is a required property for HuoheLock and cannot be null");
            }
            else
            {
                this.HouseId = HouseId;
            }
        }
        
        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// house_code
        /// </summary>
        /// <value>house_code</value>
        [DataMember(Name="house_code", EmitDefaultValue=false)]
        public string HouseCode { get; set; }

        /// <summary>
        /// room_code
        /// </summary>
        /// <value>room_code</value>
        [DataMember(Name="room_code", EmitDefaultValue=false)]
        public string RoomCode { get; set; }

        /// <summary>
        /// 门锁名
        /// </summary>
        /// <value>门锁名</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// 电量
        /// </summary>
        /// <value>电量</value>
        [DataMember(Name="power", EmitDefaultValue=false)]
        public int? Power { get; set; }

        /// <summary>
        /// 00 通信正常 01通信异常
        /// </summary>
        /// <value>00 通信正常 01通信异常</value>
        [DataMember(Name="comu_status", EmitDefaultValue=false)]
        public string ComuStatus { get; set; }

        /// <summary>
        /// 设备ip
        /// </summary>
        /// <value>设备ip</value>
        [DataMember(Name="ip", EmitDefaultValue=false)]
        public string Ip { get; set; }

        /// <summary>
        /// 用户ID
        /// </summary>
        /// <value>用户ID</value>
        [DataMember(Name="user_id", EmitDefaultValue=false)]
        public int? UserId { get; set; }

        /// <summary>
        /// 房间ID
        /// </summary>
        /// <value>房间ID</value>
        [DataMember(Name="house_id", EmitDefaultValue=false)]
        public int? HouseId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HuoheLock {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  HouseCode: ").Append(HouseCode).Append("\n");
            sb.Append("  RoomCode: ").Append(RoomCode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Power: ").Append(Power).Append("\n");
            sb.Append("  ComuStatus: ").Append(ComuStatus).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  HouseId: ").Append(HouseId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HuoheLock);
        }

        /// <summary>
        /// Returns true if HuoheLock instances are equal
        /// </summary>
        /// <param name="input">Instance of HuoheLock to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HuoheLock input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.HouseCode == input.HouseCode ||
                    (this.HouseCode != null &&
                    this.HouseCode.Equals(input.HouseCode))
                ) && 
                (
                    this.RoomCode == input.RoomCode ||
                    (this.RoomCode != null &&
                    this.RoomCode.Equals(input.RoomCode))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Power == input.Power ||
                    (this.Power != null &&
                    this.Power.Equals(input.Power))
                ) && 
                (
                    this.ComuStatus == input.ComuStatus ||
                    (this.ComuStatus != null &&
                    this.ComuStatus.Equals(input.ComuStatus))
                ) && 
                (
                    this.Ip == input.Ip ||
                    (this.Ip != null &&
                    this.Ip.Equals(input.Ip))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.HouseId == input.HouseId ||
                    (this.HouseId != null &&
                    this.HouseId.Equals(input.HouseId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.HouseCode != null)
                    hashCode = hashCode * 59 + this.HouseCode.GetHashCode();
                if (this.RoomCode != null)
                    hashCode = hashCode * 59 + this.RoomCode.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Power != null)
                    hashCode = hashCode * 59 + this.Power.GetHashCode();
                if (this.ComuStatus != null)
                    hashCode = hashCode * 59 + this.ComuStatus.GetHashCode();
                if (this.Ip != null)
                    hashCode = hashCode * 59 + this.Ip.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.HouseId != null)
                    hashCode = hashCode * 59 + this.HouseId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
