/* 
 * Version 1
 *
 * This is version 1 document
 *
 * OpenAPI spec version: 0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Elton.Phantom.Models.SwaggerDateConverter;

namespace Elton.Phantom.Models.Version1
{
    /// <summary>
    /// 发送红外指令控制
    /// </summary>
    [DataContract]
    public partial class InfraredRemote :  IEquatable<InfraredRemote>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InfraredRemote" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InfraredRemote() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InfraredRemote" /> class.
        /// </summary>
        /// <param name="Id">ID (required).</param>
        /// <param name="Name">设备的名字 (required).</param>
        /// <param name="DeviceIdentifier">设备标识字符串 cf. 总则§2.3 (required).</param>
        /// <param name="TypeId">设备类型 (required).</param>
        /// <param name="HouseId">房子ID (required).</param>
        /// <param name="Connectivity">在线状态说明 cf. 总则§? (required).</param>
        /// <param name="LastTimingTime">上一次配置的时间,以秒为单位.</param>
        /// <param name="LastSendTime">上一次发控制指令的时间,以秒为单位.</param>
        /// <param name="Inst">上一次发送的指令.</param>
        /// <param name="Status">上一次发送的状态.</param>
        public InfraredRemote(int? Id = default(int?), string Name = default(string), string DeviceIdentifier = default(string), string TypeId = default(string), int? HouseId = default(int?), string Connectivity = default(string), int? LastTimingTime = default(int?), int? LastSendTime = default(int?), string Inst = default(string), string Status = default(string))
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for InfraredRemote and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for InfraredRemote and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "DeviceIdentifier" is required (not null)
            if (DeviceIdentifier == null)
            {
                throw new InvalidDataException("DeviceIdentifier is a required property for InfraredRemote and cannot be null");
            }
            else
            {
                this.DeviceIdentifier = DeviceIdentifier;
            }
            // to ensure "TypeId" is required (not null)
            if (TypeId == null)
            {
                throw new InvalidDataException("TypeId is a required property for InfraredRemote and cannot be null");
            }
            else
            {
                this.TypeId = TypeId;
            }
            // to ensure "HouseId" is required (not null)
            if (HouseId == null)
            {
                throw new InvalidDataException("HouseId is a required property for InfraredRemote and cannot be null");
            }
            else
            {
                this.HouseId = HouseId;
            }
            // to ensure "Connectivity" is required (not null)
            if (Connectivity == null)
            {
                throw new InvalidDataException("Connectivity is a required property for InfraredRemote and cannot be null");
            }
            else
            {
                this.Connectivity = Connectivity;
            }
            this.LastTimingTime = LastTimingTime;
            this.LastSendTime = LastSendTime;
            this.Inst = Inst;
            this.Status = Status;
        }
        
        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// 设备的名字
        /// </summary>
        /// <value>设备的名字</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// 设备标识字符串 cf. 总则§2.3
        /// </summary>
        /// <value>设备标识字符串 cf. 总则§2.3</value>
        [DataMember(Name="device_identifier", EmitDefaultValue=false)]
        public string DeviceIdentifier { get; set; }

        /// <summary>
        /// 设备类型
        /// </summary>
        /// <value>设备类型</value>
        [DataMember(Name="type_id", EmitDefaultValue=false)]
        public string TypeId { get; set; }

        /// <summary>
        /// 房子ID
        /// </summary>
        /// <value>房子ID</value>
        [DataMember(Name="house_id", EmitDefaultValue=false)]
        public int? HouseId { get; set; }

        /// <summary>
        /// 在线状态说明 cf. 总则§?
        /// </summary>
        /// <value>在线状态说明 cf. 总则§?</value>
        [DataMember(Name="connectivity", EmitDefaultValue=false)]
        public string Connectivity { get; set; }

        /// <summary>
        /// 上一次配置的时间,以秒为单位
        /// </summary>
        /// <value>上一次配置的时间,以秒为单位</value>
        [DataMember(Name="last_timing_time", EmitDefaultValue=false)]
        public int? LastTimingTime { get; set; }

        /// <summary>
        /// 上一次发控制指令的时间,以秒为单位
        /// </summary>
        /// <value>上一次发控制指令的时间,以秒为单位</value>
        [DataMember(Name="last_send_time", EmitDefaultValue=false)]
        public int? LastSendTime { get; set; }

        /// <summary>
        /// 上一次发送的指令
        /// </summary>
        /// <value>上一次发送的指令</value>
        [DataMember(Name="inst", EmitDefaultValue=false)]
        public string Inst { get; set; }

        /// <summary>
        /// 上一次发送的状态
        /// </summary>
        /// <value>上一次发送的状态</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InfraredRemote {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DeviceIdentifier: ").Append(DeviceIdentifier).Append("\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("  HouseId: ").Append(HouseId).Append("\n");
            sb.Append("  Connectivity: ").Append(Connectivity).Append("\n");
            sb.Append("  LastTimingTime: ").Append(LastTimingTime).Append("\n");
            sb.Append("  LastSendTime: ").Append(LastSendTime).Append("\n");
            sb.Append("  Inst: ").Append(Inst).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InfraredRemote);
        }

        /// <summary>
        /// Returns true if InfraredRemote instances are equal
        /// </summary>
        /// <param name="input">Instance of InfraredRemote to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InfraredRemote input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.DeviceIdentifier == input.DeviceIdentifier ||
                    (this.DeviceIdentifier != null &&
                    this.DeviceIdentifier.Equals(input.DeviceIdentifier))
                ) && 
                (
                    this.TypeId == input.TypeId ||
                    (this.TypeId != null &&
                    this.TypeId.Equals(input.TypeId))
                ) && 
                (
                    this.HouseId == input.HouseId ||
                    (this.HouseId != null &&
                    this.HouseId.Equals(input.HouseId))
                ) && 
                (
                    this.Connectivity == input.Connectivity ||
                    (this.Connectivity != null &&
                    this.Connectivity.Equals(input.Connectivity))
                ) && 
                (
                    this.LastTimingTime == input.LastTimingTime ||
                    (this.LastTimingTime != null &&
                    this.LastTimingTime.Equals(input.LastTimingTime))
                ) && 
                (
                    this.LastSendTime == input.LastSendTime ||
                    (this.LastSendTime != null &&
                    this.LastSendTime.Equals(input.LastSendTime))
                ) && 
                (
                    this.Inst == input.Inst ||
                    (this.Inst != null &&
                    this.Inst.Equals(input.Inst))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.DeviceIdentifier != null)
                    hashCode = hashCode * 59 + this.DeviceIdentifier.GetHashCode();
                if (this.TypeId != null)
                    hashCode = hashCode * 59 + this.TypeId.GetHashCode();
                if (this.HouseId != null)
                    hashCode = hashCode * 59 + this.HouseId.GetHashCode();
                if (this.Connectivity != null)
                    hashCode = hashCode * 59 + this.Connectivity.GetHashCode();
                if (this.LastTimingTime != null)
                    hashCode = hashCode * 59 + this.LastTimingTime.GetHashCode();
                if (this.LastSendTime != null)
                    hashCode = hashCode * 59 + this.LastSendTime.GetHashCode();
                if (this.Inst != null)
                    hashCode = hashCode * 59 + this.Inst.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
