/* 
 * Version 1
 *
 * This is version 1 document
 *
 * OpenAPI spec version: 0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Elton.Phantom.Models.SwaggerDateConverter;

namespace Elton.Phantom.Models.Version1
{
    /// <summary>
    /// 固化IFTTT情景
    /// </summary>
    [DataContract]
    public partial class ModelSwitch :  IEquatable<ModelSwitch>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelSwitch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModelSwitch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelSwitch" /> class.
        /// </summary>
        /// <param name="Id">ID (required).</param>
        /// <param name="DeviceIdentifier">设备标识字符串 cf. 总则§2.3 (required).</param>
        /// <param name="TurnedOn">是否已开机 (required).</param>
        /// <param name="OwnDevice">是不是自己的设备 (required).</param>
        /// <param name="Name">设备的名字 (required).</param>
        /// <param name="Position">排序用的序号.</param>
        /// <param name="DeviceIp">设备地址.</param>
        /// <param name="RouterId">路由ID.</param>
        /// <param name="HouseId">房子ID.</param>
        /// <param name="Connectivity">在线状态说明 cf. 总则§?.</param>
        /// <param name="AccumulatedUsageTime">累计使用时长.</param>
        /// <param name="Mode">模式，mode＝1为使用简单开关设置，mode&#x3D;2为使用高级开关设置，mode&#x3D;3为使用情景模式设置，mode&#x3D;4已经过时了，mode&#x3D;5表示这个开关正出现在某一个场景里,mode&#x3D;6表示该开关已配置一个IFTTT情景.</param>
        /// <param name="Brightness1">亮度1, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null.</param>
        /// <param name="Hue1">色温1, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null.</param>
        /// <param name="Brightness2">亮度2, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null.</param>
        /// <param name="Hue2">色温2, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null.</param>
        /// <param name="Brightness3">亮度3, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null.</param>
        /// <param name="Hue3">色温3, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null.</param>
        /// <param name="IsClear">情景数据是否已清空.</param>
        /// <param name="Scenario1Id">情景模式轮换之第1个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null.</param>
        /// <param name="Scenario2Id">情景模式轮换之第2个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null.</param>
        /// <param name="Scenario3Id">情景模式轮换之第3个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null.</param>
        /// <param name="Scenario4Id">情景模式轮换之第4个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null.</param>
        /// <param name="CreatedAt">记录的创建日期.</param>
        /// <param name="UpdatedAt">记录的更新日期.</param>
        /// <param name="DeathQrCode">设备的死亡二维码，即删除后的设备会获得的一个二维码，           这样误删或是送人都可以用这个二维码，或是自己的设备坏了也可以用.</param>
        /// <param name="Recipe">使用这个开关的场景.</param>
        public ModelSwitch(int? Id = default(int?), string DeviceIdentifier = default(string), int? TurnedOn = default(int?), bool? OwnDevice = default(bool?), string Name = default(string), int? Position = default(int?), int? DeviceIp = default(int?), int? RouterId = default(int?), int? HouseId = default(int?), string Connectivity = default(string), int? AccumulatedUsageTime = default(int?), int? Mode = default(int?), float? Brightness1 = default(float?), float? Hue1 = default(float?), float? Brightness2 = default(float?), float? Hue2 = default(float?), float? Brightness3 = default(float?), float? Hue3 = default(float?), bool? IsClear = default(bool?), int? Scenario1Id = default(int?), int? Scenario2Id = default(int?), int? Scenario3Id = default(int?), int? Scenario4Id = default(int?), DateTime? CreatedAt = default(DateTime?), DateTime? UpdatedAt = default(DateTime?), QrCode DeathQrCode = default(QrCode), Recipe Recipe = default(Recipe))
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for ModelSwitch and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "DeviceIdentifier" is required (not null)
            if (DeviceIdentifier == null)
            {
                throw new InvalidDataException("DeviceIdentifier is a required property for ModelSwitch and cannot be null");
            }
            else
            {
                this.DeviceIdentifier = DeviceIdentifier;
            }
            // to ensure "TurnedOn" is required (not null)
            if (TurnedOn == null)
            {
                throw new InvalidDataException("TurnedOn is a required property for ModelSwitch and cannot be null");
            }
            else
            {
                this.TurnedOn = TurnedOn;
            }
            // to ensure "OwnDevice" is required (not null)
            if (OwnDevice == null)
            {
                throw new InvalidDataException("OwnDevice is a required property for ModelSwitch and cannot be null");
            }
            else
            {
                this.OwnDevice = OwnDevice;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for ModelSwitch and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            this.Position = Position;
            this.DeviceIp = DeviceIp;
            this.RouterId = RouterId;
            this.HouseId = HouseId;
            this.Connectivity = Connectivity;
            this.AccumulatedUsageTime = AccumulatedUsageTime;
            this.Mode = Mode;
            this.Brightness1 = Brightness1;
            this.Hue1 = Hue1;
            this.Brightness2 = Brightness2;
            this.Hue2 = Hue2;
            this.Brightness3 = Brightness3;
            this.Hue3 = Hue3;
            this.IsClear = IsClear;
            this.Scenario1Id = Scenario1Id;
            this.Scenario2Id = Scenario2Id;
            this.Scenario3Id = Scenario3Id;
            this.Scenario4Id = Scenario4Id;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
            this.DeathQrCode = DeathQrCode;
            this.Recipe = Recipe;
        }
        
        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// 设备标识字符串 cf. 总则§2.3
        /// </summary>
        /// <value>设备标识字符串 cf. 总则§2.3</value>
        [DataMember(Name="device_identifier", EmitDefaultValue=false)]
        public string DeviceIdentifier { get; set; }

        /// <summary>
        /// 是否已开机
        /// </summary>
        /// <value>是否已开机</value>
        [DataMember(Name="turned_on", EmitDefaultValue=false)]
        public int? TurnedOn { get; set; }

        /// <summary>
        /// 是不是自己的设备
        /// </summary>
        /// <value>是不是自己的设备</value>
        [DataMember(Name="own_device?", EmitDefaultValue=false)]
        public bool? OwnDevice { get; set; }

        /// <summary>
        /// 设备的名字
        /// </summary>
        /// <value>设备的名字</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// 排序用的序号
        /// </summary>
        /// <value>排序用的序号</value>
        [DataMember(Name="position", EmitDefaultValue=false)]
        public int? Position { get; set; }

        /// <summary>
        /// 设备地址
        /// </summary>
        /// <value>设备地址</value>
        [DataMember(Name="device_ip", EmitDefaultValue=false)]
        public int? DeviceIp { get; set; }

        /// <summary>
        /// 路由ID
        /// </summary>
        /// <value>路由ID</value>
        [DataMember(Name="router_id", EmitDefaultValue=false)]
        public int? RouterId { get; set; }

        /// <summary>
        /// 房子ID
        /// </summary>
        /// <value>房子ID</value>
        [DataMember(Name="house_id", EmitDefaultValue=false)]
        public int? HouseId { get; set; }

        /// <summary>
        /// 在线状态说明 cf. 总则§?
        /// </summary>
        /// <value>在线状态说明 cf. 总则§?</value>
        [DataMember(Name="connectivity", EmitDefaultValue=false)]
        public string Connectivity { get; set; }

        /// <summary>
        /// 累计使用时长
        /// </summary>
        /// <value>累计使用时长</value>
        [DataMember(Name="accumulated_usage_time", EmitDefaultValue=false)]
        public int? AccumulatedUsageTime { get; set; }

        /// <summary>
        /// 模式，mode＝1为使用简单开关设置，mode&#x3D;2为使用高级开关设置，mode&#x3D;3为使用情景模式设置，mode&#x3D;4已经过时了，mode&#x3D;5表示这个开关正出现在某一个场景里,mode&#x3D;6表示该开关已配置一个IFTTT情景
        /// </summary>
        /// <value>模式，mode＝1为使用简单开关设置，mode&#x3D;2为使用高级开关设置，mode&#x3D;3为使用情景模式设置，mode&#x3D;4已经过时了，mode&#x3D;5表示这个开关正出现在某一个场景里,mode&#x3D;6表示该开关已配置一个IFTTT情景</value>
        [DataMember(Name="mode", EmitDefaultValue=false)]
        public int? Mode { get; set; }

        /// <summary>
        /// 亮度1, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null
        /// </summary>
        /// <value>亮度1, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null</value>
        [DataMember(Name="brightness1", EmitDefaultValue=false)]
        public float? Brightness1 { get; set; }

        /// <summary>
        /// 色温1, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null
        /// </summary>
        /// <value>色温1, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null</value>
        [DataMember(Name="hue1", EmitDefaultValue=false)]
        public float? Hue1 { get; set; }

        /// <summary>
        /// 亮度2, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null
        /// </summary>
        /// <value>亮度2, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null</value>
        [DataMember(Name="brightness2", EmitDefaultValue=false)]
        public float? Brightness2 { get; set; }

        /// <summary>
        /// 色温2, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null
        /// </summary>
        /// <value>色温2, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null</value>
        [DataMember(Name="hue2", EmitDefaultValue=false)]
        public float? Hue2 { get; set; }

        /// <summary>
        /// 亮度3, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null
        /// </summary>
        /// <value>亮度3, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null</value>
        [DataMember(Name="brightness3", EmitDefaultValue=false)]
        public float? Brightness3 { get; set; }

        /// <summary>
        /// 色温3, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null
        /// </summary>
        /// <value>色温3, mode&#x3D;1无效, mode&#x3D;3无效, 未配置则为null</value>
        [DataMember(Name="hue3", EmitDefaultValue=false)]
        public float? Hue3 { get; set; }

        /// <summary>
        /// 情景数据是否已清空
        /// </summary>
        /// <value>情景数据是否已清空</value>
        [DataMember(Name="is_clear", EmitDefaultValue=false)]
        public bool? IsClear { get; set; }

        /// <summary>
        /// 情景模式轮换之第1个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null
        /// </summary>
        /// <value>情景模式轮换之第1个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null</value>
        [DataMember(Name="scenario1_id", EmitDefaultValue=false)]
        public int? Scenario1Id { get; set; }

        /// <summary>
        /// 情景模式轮换之第2个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null
        /// </summary>
        /// <value>情景模式轮换之第2个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null</value>
        [DataMember(Name="scenario2_id", EmitDefaultValue=false)]
        public int? Scenario2Id { get; set; }

        /// <summary>
        /// 情景模式轮换之第3个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null
        /// </summary>
        /// <value>情景模式轮换之第3个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null</value>
        [DataMember(Name="scenario3_id", EmitDefaultValue=false)]
        public int? Scenario3Id { get; set; }

        /// <summary>
        /// 情景模式轮换之第4个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null
        /// </summary>
        /// <value>情景模式轮换之第4个情景模式的ID, mode&#x3D;1无效, mode&#x3D;2无效, 未配置则为null</value>
        [DataMember(Name="scenario4_id", EmitDefaultValue=false)]
        public int? Scenario4Id { get; set; }

        /// <summary>
        /// 记录的创建日期
        /// </summary>
        /// <value>记录的创建日期</value>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// 记录的更新日期
        /// </summary>
        /// <value>记录的更新日期</value>
        [DataMember(Name="updated_at", EmitDefaultValue=false)]
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// 设备的死亡二维码，即删除后的设备会获得的一个二维码，           这样误删或是送人都可以用这个二维码，或是自己的设备坏了也可以用
        /// </summary>
        /// <value>设备的死亡二维码，即删除后的设备会获得的一个二维码，           这样误删或是送人都可以用这个二维码，或是自己的设备坏了也可以用</value>
        [DataMember(Name="death_qr_code", EmitDefaultValue=false)]
        public QrCode DeathQrCode { get; set; }

        /// <summary>
        /// 使用这个开关的场景
        /// </summary>
        /// <value>使用这个开关的场景</value>
        [DataMember(Name="recipe", EmitDefaultValue=false)]
        public Recipe Recipe { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelSwitch {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DeviceIdentifier: ").Append(DeviceIdentifier).Append("\n");
            sb.Append("  TurnedOn: ").Append(TurnedOn).Append("\n");
            sb.Append("  OwnDevice: ").Append(OwnDevice).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  DeviceIp: ").Append(DeviceIp).Append("\n");
            sb.Append("  RouterId: ").Append(RouterId).Append("\n");
            sb.Append("  HouseId: ").Append(HouseId).Append("\n");
            sb.Append("  Connectivity: ").Append(Connectivity).Append("\n");
            sb.Append("  AccumulatedUsageTime: ").Append(AccumulatedUsageTime).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  Brightness1: ").Append(Brightness1).Append("\n");
            sb.Append("  Hue1: ").Append(Hue1).Append("\n");
            sb.Append("  Brightness2: ").Append(Brightness2).Append("\n");
            sb.Append("  Hue2: ").Append(Hue2).Append("\n");
            sb.Append("  Brightness3: ").Append(Brightness3).Append("\n");
            sb.Append("  Hue3: ").Append(Hue3).Append("\n");
            sb.Append("  IsClear: ").Append(IsClear).Append("\n");
            sb.Append("  Scenario1Id: ").Append(Scenario1Id).Append("\n");
            sb.Append("  Scenario2Id: ").Append(Scenario2Id).Append("\n");
            sb.Append("  Scenario3Id: ").Append(Scenario3Id).Append("\n");
            sb.Append("  Scenario4Id: ").Append(Scenario4Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  DeathQrCode: ").Append(DeathQrCode).Append("\n");
            sb.Append("  Recipe: ").Append(Recipe).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModelSwitch);
        }

        /// <summary>
        /// Returns true if ModelSwitch instances are equal
        /// </summary>
        /// <param name="input">Instance of ModelSwitch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelSwitch input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.DeviceIdentifier == input.DeviceIdentifier ||
                    (this.DeviceIdentifier != null &&
                    this.DeviceIdentifier.Equals(input.DeviceIdentifier))
                ) && 
                (
                    this.TurnedOn == input.TurnedOn ||
                    (this.TurnedOn != null &&
                    this.TurnedOn.Equals(input.TurnedOn))
                ) && 
                (
                    this.OwnDevice == input.OwnDevice ||
                    (this.OwnDevice != null &&
                    this.OwnDevice.Equals(input.OwnDevice))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Position == input.Position ||
                    (this.Position != null &&
                    this.Position.Equals(input.Position))
                ) && 
                (
                    this.DeviceIp == input.DeviceIp ||
                    (this.DeviceIp != null &&
                    this.DeviceIp.Equals(input.DeviceIp))
                ) && 
                (
                    this.RouterId == input.RouterId ||
                    (this.RouterId != null &&
                    this.RouterId.Equals(input.RouterId))
                ) && 
                (
                    this.HouseId == input.HouseId ||
                    (this.HouseId != null &&
                    this.HouseId.Equals(input.HouseId))
                ) && 
                (
                    this.Connectivity == input.Connectivity ||
                    (this.Connectivity != null &&
                    this.Connectivity.Equals(input.Connectivity))
                ) && 
                (
                    this.AccumulatedUsageTime == input.AccumulatedUsageTime ||
                    (this.AccumulatedUsageTime != null &&
                    this.AccumulatedUsageTime.Equals(input.AccumulatedUsageTime))
                ) && 
                (
                    this.Mode == input.Mode ||
                    (this.Mode != null &&
                    this.Mode.Equals(input.Mode))
                ) && 
                (
                    this.Brightness1 == input.Brightness1 ||
                    (this.Brightness1 != null &&
                    this.Brightness1.Equals(input.Brightness1))
                ) && 
                (
                    this.Hue1 == input.Hue1 ||
                    (this.Hue1 != null &&
                    this.Hue1.Equals(input.Hue1))
                ) && 
                (
                    this.Brightness2 == input.Brightness2 ||
                    (this.Brightness2 != null &&
                    this.Brightness2.Equals(input.Brightness2))
                ) && 
                (
                    this.Hue2 == input.Hue2 ||
                    (this.Hue2 != null &&
                    this.Hue2.Equals(input.Hue2))
                ) && 
                (
                    this.Brightness3 == input.Brightness3 ||
                    (this.Brightness3 != null &&
                    this.Brightness3.Equals(input.Brightness3))
                ) && 
                (
                    this.Hue3 == input.Hue3 ||
                    (this.Hue3 != null &&
                    this.Hue3.Equals(input.Hue3))
                ) && 
                (
                    this.IsClear == input.IsClear ||
                    (this.IsClear != null &&
                    this.IsClear.Equals(input.IsClear))
                ) && 
                (
                    this.Scenario1Id == input.Scenario1Id ||
                    (this.Scenario1Id != null &&
                    this.Scenario1Id.Equals(input.Scenario1Id))
                ) && 
                (
                    this.Scenario2Id == input.Scenario2Id ||
                    (this.Scenario2Id != null &&
                    this.Scenario2Id.Equals(input.Scenario2Id))
                ) && 
                (
                    this.Scenario3Id == input.Scenario3Id ||
                    (this.Scenario3Id != null &&
                    this.Scenario3Id.Equals(input.Scenario3Id))
                ) && 
                (
                    this.Scenario4Id == input.Scenario4Id ||
                    (this.Scenario4Id != null &&
                    this.Scenario4Id.Equals(input.Scenario4Id))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                ) && 
                (
                    this.DeathQrCode == input.DeathQrCode ||
                    (this.DeathQrCode != null &&
                    this.DeathQrCode.Equals(input.DeathQrCode))
                ) && 
                (
                    this.Recipe == input.Recipe ||
                    (this.Recipe != null &&
                    this.Recipe.Equals(input.Recipe))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.DeviceIdentifier != null)
                    hashCode = hashCode * 59 + this.DeviceIdentifier.GetHashCode();
                if (this.TurnedOn != null)
                    hashCode = hashCode * 59 + this.TurnedOn.GetHashCode();
                if (this.OwnDevice != null)
                    hashCode = hashCode * 59 + this.OwnDevice.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Position != null)
                    hashCode = hashCode * 59 + this.Position.GetHashCode();
                if (this.DeviceIp != null)
                    hashCode = hashCode * 59 + this.DeviceIp.GetHashCode();
                if (this.RouterId != null)
                    hashCode = hashCode * 59 + this.RouterId.GetHashCode();
                if (this.HouseId != null)
                    hashCode = hashCode * 59 + this.HouseId.GetHashCode();
                if (this.Connectivity != null)
                    hashCode = hashCode * 59 + this.Connectivity.GetHashCode();
                if (this.AccumulatedUsageTime != null)
                    hashCode = hashCode * 59 + this.AccumulatedUsageTime.GetHashCode();
                if (this.Mode != null)
                    hashCode = hashCode * 59 + this.Mode.GetHashCode();
                if (this.Brightness1 != null)
                    hashCode = hashCode * 59 + this.Brightness1.GetHashCode();
                if (this.Hue1 != null)
                    hashCode = hashCode * 59 + this.Hue1.GetHashCode();
                if (this.Brightness2 != null)
                    hashCode = hashCode * 59 + this.Brightness2.GetHashCode();
                if (this.Hue2 != null)
                    hashCode = hashCode * 59 + this.Hue2.GetHashCode();
                if (this.Brightness3 != null)
                    hashCode = hashCode * 59 + this.Brightness3.GetHashCode();
                if (this.Hue3 != null)
                    hashCode = hashCode * 59 + this.Hue3.GetHashCode();
                if (this.IsClear != null)
                    hashCode = hashCode * 59 + this.IsClear.GetHashCode();
                if (this.Scenario1Id != null)
                    hashCode = hashCode * 59 + this.Scenario1Id.GetHashCode();
                if (this.Scenario2Id != null)
                    hashCode = hashCode * 59 + this.Scenario2Id.GetHashCode();
                if (this.Scenario3Id != null)
                    hashCode = hashCode * 59 + this.Scenario3Id.GetHashCode();
                if (this.Scenario4Id != null)
                    hashCode = hashCode * 59 + this.Scenario4Id.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                if (this.UpdatedAt != null)
                    hashCode = hashCode * 59 + this.UpdatedAt.GetHashCode();
                if (this.DeathQrCode != null)
                    hashCode = hashCode * 59 + this.DeathQrCode.GetHashCode();
                if (this.Recipe != null)
                    hashCode = hashCode * 59 + this.Recipe.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
