/* 
 * Version 1
 *
 * This is version 1 document
 *
 * OpenAPI spec version: 0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Elton.Phantom.Models.SwaggerDateConverter;

namespace Elton.Phantom.Models.Version1
{
    /// <summary>
    /// 控制净水器
    /// </summary>
    [DataContract]
    public partial class WaterPurifier :  IEquatable<WaterPurifier>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WaterPurifier" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WaterPurifier() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WaterPurifier" /> class.
        /// </summary>
        /// <param name="Id">ID (required).</param>
        /// <param name="Name">名字 (required).</param>
        /// <param name="UserId">账户ID (required).</param>
        /// <param name="HouseId">房间ID.</param>
        /// <param name="Flows">累计流量.</param>
        /// <param name="Tds">Tds.</param>
        /// <param name="Filters">ID (required).</param>
        /// <param name="DeviceCategory">设备类别.</param>
        /// <param name="Capability">Capability.</param>
        /// <param name="Status">Status.</param>
        public WaterPurifier(int? Id = default(int?), string Name = default(string), int? UserId = default(int?), int? HouseId = default(int?), int? Flows = default(int?), WaterPurifierTds Tds = default(WaterPurifierTds), GmFilter Filters = default(GmFilter), string DeviceCategory = default(string), string Capability = default(string), string Status = default(string))
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for WaterPurifier and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for WaterPurifier and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "UserId" is required (not null)
            if (UserId == null)
            {
                throw new InvalidDataException("UserId is a required property for WaterPurifier and cannot be null");
            }
            else
            {
                this.UserId = UserId;
            }
            // to ensure "Filters" is required (not null)
            if (Filters == null)
            {
                throw new InvalidDataException("Filters is a required property for WaterPurifier and cannot be null");
            }
            else
            {
                this.Filters = Filters;
            }
            this.HouseId = HouseId;
            this.Flows = Flows;
            this.Tds = Tds;
            this.DeviceCategory = DeviceCategory;
            this.Capability = Capability;
            this.Status = Status;
        }
        
        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// 名字
        /// </summary>
        /// <value>名字</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// 账户ID
        /// </summary>
        /// <value>账户ID</value>
        [DataMember(Name="user_id", EmitDefaultValue=false)]
        public int? UserId { get; set; }

        /// <summary>
        /// 房间ID
        /// </summary>
        /// <value>房间ID</value>
        [DataMember(Name="house_id", EmitDefaultValue=false)]
        public int? HouseId { get; set; }

        /// <summary>
        /// 累计流量
        /// </summary>
        /// <value>累计流量</value>
        [DataMember(Name="flows", EmitDefaultValue=false)]
        public int? Flows { get; set; }

        /// <summary>
        /// Gets or Sets Tds
        /// </summary>
        [DataMember(Name="tds", EmitDefaultValue=false)]
        public WaterPurifierTds Tds { get; set; }

        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [DataMember(Name="filters", EmitDefaultValue=false)]
        public GmFilter Filters { get; set; }

        /// <summary>
        /// 设备类别
        /// </summary>
        /// <value>设备类别</value>
        [DataMember(Name="device_category", EmitDefaultValue=false)]
        public string DeviceCategory { get; set; }

        /// <summary>
        /// Gets or Sets Capability
        /// </summary>
        [DataMember(Name="capability", EmitDefaultValue=false)]
        public string Capability { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WaterPurifier {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  HouseId: ").Append(HouseId).Append("\n");
            sb.Append("  Flows: ").Append(Flows).Append("\n");
            sb.Append("  Tds: ").Append(Tds).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("  DeviceCategory: ").Append(DeviceCategory).Append("\n");
            sb.Append("  Capability: ").Append(Capability).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WaterPurifier);
        }

        /// <summary>
        /// Returns true if WaterPurifier instances are equal
        /// </summary>
        /// <param name="input">Instance of WaterPurifier to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WaterPurifier input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.HouseId == input.HouseId ||
                    (this.HouseId != null &&
                    this.HouseId.Equals(input.HouseId))
                ) && 
                (
                    this.Flows == input.Flows ||
                    (this.Flows != null &&
                    this.Flows.Equals(input.Flows))
                ) && 
                (
                    this.Tds == input.Tds ||
                    (this.Tds != null &&
                    this.Tds.Equals(input.Tds))
                ) && 
                (
                    this.Filters == input.Filters ||
                    (this.Filters != null &&
                    this.Filters.Equals(input.Filters))
                ) && 
                (
                    this.DeviceCategory == input.DeviceCategory ||
                    (this.DeviceCategory != null &&
                    this.DeviceCategory.Equals(input.DeviceCategory))
                ) && 
                (
                    this.Capability == input.Capability ||
                    (this.Capability != null &&
                    this.Capability.Equals(input.Capability))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.HouseId != null)
                    hashCode = hashCode * 59 + this.HouseId.GetHashCode();
                if (this.Flows != null)
                    hashCode = hashCode * 59 + this.Flows.GetHashCode();
                if (this.Tds != null)
                    hashCode = hashCode * 59 + this.Tds.GetHashCode();
                if (this.Filters != null)
                    hashCode = hashCode * 59 + this.Filters.GetHashCode();
                if (this.DeviceCategory != null)
                    hashCode = hashCode * 59 + this.DeviceCategory.GetHashCode();
                if (this.Capability != null)
                    hashCode = hashCode * 59 + this.Capability.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
